# encoding: UTF-8
# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your
# database schema. If you need to create the application database on another
# system, you should be using db:schema:load, not running all the migrations
# from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended to check this file into your version control system.

ActiveRecord::Schema.define(:version => 20121116224257) do

  create_table "clients", :force => true do |t|
    t.string   "first_name"
    t.string   "last_name"
    t.string   "identifier"
    t.date     "date_of_birth"
    t.string   "primary_phone"
    t.text     "notes"
    t.integer  "user_id"
    t.datetime "created_at",    :null => false
    t.datetime "updated_at",    :null => false
  end

  add_index "clients", ["user_id"], :name => "index_clients_on_user_id"

  create_table "entries", :force => true do |t|
    t.datetime "created_at",                                                                  :null => false
    t.datetime "updated_at",                                                                  :null => false
    t.integer  "client_id"
    t.string   "mse_form_number"
    t.string   "name"
    t.date     "date_of_birth"
    t.string   "gender"
    t.text     "circumstance_of_presentation"
    t.text     "appearance_weight_notes"
    t.text     "appearance_hair_notes"
    t.text     "appearance_other_notes"
    t.text     "appearance_grooming_notes"
    t.text     "appearance_dress_notes"
    t.text     "behavior_walk_notes"
    t.text     "behavior_combativeness_notes"
    t.text     "behavior_repetition_notes"
    t.text     "behavior_overactivity_notes"
    t.text     "behavior_catatonia_notes"
    t.text     "speech_rate_notes"
    t.text     "speech_intelligibility_notes"
    t.text     "speech_volume_notes"
    t.text     "speech_quality_notes"
    t.text     "speech_quantity_notes"
    t.text     "attitude_notes"
    t.text     "affect_mood_notes"
    t.text     "affect_expression_notes"
    t.text     "affect_appropriateness_notes"
    t.text     "perception_hallucinations_notes"
    t.text     "perception_disassociation_notes"
    t.text     "perception_agnosia_notes"
    t.boolean  "current_treatment_psychotherapy"
    t.text     "current_treatment_psychotherapy_notes"
    t.boolean  "current_treatment_psychoactive_medication"
    t.text     "current_treatment_psychoactive_medication_notes"
    t.string   "appearance_weight"
    t.string   "appearance_hair"
    t.string   "appearance_other"
    t.string   "appearance_grooming"
    t.string   "appearance_dress"
    t.string   "behavior_walk"
    t.string   "behavior_combativeness"
    t.string   "behavior_repetition"
    t.string   "behavior_overactivity"
    t.string   "behavior_catatonia"
    t.string   "speech_rate"
    t.string   "speech_intelligibility"
    t.string   "speech_volume"
    t.string   "speech_quality"
    t.string   "speech_quantity"
    t.string   "attitude"
    t.string   "affect_mood"
    t.string   "affect_expression"
    t.string   "affect_appropriateness"
    t.string   "perception_hallucinations"
    t.string   "perception_disassociation"
    t.string   "perception_agnosia"
    t.boolean  "appearance_weight_obese"
    t.boolean  "appearance_weight_overweight"
    t.boolean  "appearance_weight_underweight"
    t.boolean  "appearance_weight_emaciated"
    t.boolean  "appearance_weight_unremarkable"
    t.boolean  "appearance_hair_bizarre"
    t.boolean  "appearance_hair_unnatural"
    t.boolean  "appearance_hair_unshaven"
    t.boolean  "appearance_hair_unremarkable"
    t.boolean  "appearance_other_wounds"
    t.boolean  "appearance_other_scars"
    t.boolean  "appearance_other_tattoos"
    t.boolean  "appearance_other_jewelry"
    t.boolean  "appearance_other_glasses"
    t.boolean  "appearance_other_dental_braces"
    t.boolean  "appearance_other_unremarkable"
    t.boolean  "appearance_grooming_disheveled"
    t.boolean  "appearance_grooming_soiled"
    t.boolean  "appearance_grooming_body_odor"
    t.boolean  "appearance_grooming_halitosis"
    t.boolean  "appearance_grooming_unremarkable"
    t.boolean  "appearance_dress_undressed"
    t.boolean  "appearance_dress_underdressed"
    t.boolean  "appearance_dress_overdressed"
    t.boolean  "appearance_dress_bizarre"
    t.boolean  "appearance_dress_militaristic"
    t.boolean  "appearance_dress_unremarkable"
    t.boolean  "behavior_walk_gait_march"
    t.boolean  "behavior_walk_limp"
    t.boolean  "behavior_walk_shuffle"
    t.boolean  "behavior_walk_assisted"
    t.boolean  "behavior_walk_unremarkable"
    t.boolean  "behavior_combativeness_cataplexy"
    t.boolean  "behavior_combativeness_aggressive"
    t.boolean  "behavior_combativeness_unremarkable"
    t.boolean  "behavior_repetition_gestures"
    t.boolean  "behavior_repetition_twitches"
    t.boolean  "behavior_repetition_stereotypical"
    t.boolean  "behavior_repetition_automatism"
    t.boolean  "behavior_repetition_mimicry"
    t.boolean  "behavior_repetition_echopraxia"
    t.boolean  "behavior_repetition_unremarkable"
    t.boolean  "behavior_overactivity_psychomotor_agitation"
    t.boolean  "behavior_overactivity_hyperactivity"
    t.boolean  "behavior_overactivity_tic"
    t.boolean  "behavior_overactivity_sleepwalking"
    t.boolean  "behavior_overactivity_compulsion"
    t.boolean  "behavior_overactivity_unremarkable"
    t.boolean  "behavior_catatonia_catalepsy"
    t.boolean  "behavior_catatonia_exited"
    t.boolean  "behavior_catatonia_stupor"
    t.boolean  "behavior_catatonia_rigidity"
    t.boolean  "behavior_catatonia_posturing"
    t.boolean  "behavior_catatonia_cerea_flexibilitas"
    t.boolean  "behavior_catatonia_negativism"
    t.boolean  "behavior_catatonia_unremarkable"
    t.boolean  "speech_rate_rapid"
    t.boolean  "speech_rate_slow"
    t.boolean  "speech_rate_unremarkable"
    t.boolean  "speech_intelligibility_slurred"
    t.boolean  "speech_intelligibility_mumbled"
    t.boolean  "speech_intelligibility_stutters"
    t.boolean  "speech_intelligibility_accented"
    t.boolean  "speech_intelligibility_unremarkable"
    t.boolean  "speech_volume_loud"
    t.boolean  "speech_volume_whispered"
    t.boolean  "speech_volume_unremarkable"
    t.boolean  "speech_quality_hesitant"
    t.boolean  "speech_quality_emotional"
    t.boolean  "speech_quality_monotonous"
    t.boolean  "speech_quality_stereotypical"
    t.boolean  "speech_quality_unspontaneous"
    t.boolean  "speech_quality_echolalia"
    t.boolean  "speech_quality_verbigerative"
    t.boolean  "speech_quality_unremarkable"
    t.boolean  "speech_quantity_garrulous"
    t.boolean  "speech_quantity_talkative"
    t.boolean  "speech_quantity_responsive"
    t.boolean  "speech_quantity_taciturn"
    t.boolean  "speech_quantity_mutism"
    t.boolean  "speech_quantity_unremarkable"
    t.boolean  "attitude_seductive"
    t.boolean  "attitude_playful"
    t.boolean  "attitude_ingratiating"
    t.boolean  "attitude_friendly"
    t.boolean  "attitude_cooperative"
    t.boolean  "attitude_interested"
    t.boolean  "attitude_attentive"
    t.boolean  "attitude_frank"
    t.boolean  "attitude_indifferent"
    t.boolean  "attitude_evasive"
    t.boolean  "attitude_defensive"
    t.boolean  "attitude_hostile"
    t.boolean  "attitude_unremarkable"
    t.boolean  "affect_mood_ecstatic"
    t.boolean  "affect_mood_euphoric"
    t.boolean  "affect_mood_expansive"
    t.boolean  "affect_mood_elevated"
    t.boolean  "affect_mood_euthymic"
    t.boolean  "affect_mood_dysphoric"
    t.boolean  "affect_mood_anhedonic"
    t.boolean  "affect_mood_depressed"
    t.boolean  "affect_mood_alexithymic"
    t.boolean  "affect_mood_grieving"
    t.boolean  "affect_mood_panicked"
    t.boolean  "affect_mood_fearful"
    t.boolean  "affect_mood_anxious"
    t.boolean  "affect_mood_tense"
    t.boolean  "affect_mood_agitated"
    t.boolean  "affect_mood_apathetic"
    t.boolean  "affect_mood_irritable"
    t.boolean  "affect_mood_angry"
    t.boolean  "affect_mood_ambivalence"
    t.boolean  "affect_mood_mood_swings"
    t.boolean  "affect_mood_anorexia"
    t.boolean  "affect_mood_insomnia"
    t.boolean  "affect_mood_hypersomnia"
    t.boolean  "affect_mood_diminshed_libido"
    t.boolean  "affect_mood_constipation"
    t.boolean  "affect_mood_unremarkable"
    t.boolean  "affect_expression_normal"
    t.boolean  "affect_expression_restricted"
    t.boolean  "affect_expression_blunted"
    t.boolean  "affect_expression_flat"
    t.boolean  "affect_expression_unremarkable"
    t.boolean  "affect_appropriateness_appropriate"
    t.boolean  "affect_appropriateness_inappropriate"
    t.boolean  "affect_appropriateness_labile"
    t.boolean  "perception_hallucinations_hypnagogic"
    t.boolean  "perception_hallucinations_hypnopompic"
    t.boolean  "perception_hallucinations_auditory"
    t.boolean  "perception_hallucinations_visual"
    t.boolean  "perception_hallucinations_olfactory"
    t.boolean  "perception_hallucinations_gustatory"
    t.boolean  "perception_hallucinations_tactile"
    t.boolean  "perception_hallucinations_somatic"
    t.boolean  "perception_hallucinations_lilliputian"
    t.boolean  "perception_hallucinations_mood_congruent"
    t.boolean  "perception_hallucinations_mood_incongruent"
    t.boolean  "perception_hallucinations_hallucinosis"
    t.boolean  "perception_hallucinations_synethesia"
    t.boolean  "perception_hallucinations_trailing"
    t.boolean  "perception_hallucinations_unremarkable"
    t.boolean  "perception_disassociation_hysterical_anesthesia"
    t.boolean  "perception_disassociation_macropsia"
    t.boolean  "perception_disassociation_micropsia"
    t.boolean  "perception_disassociation_depersonalization"
    t.boolean  "perception_disassociation_derealization"
    t.boolean  "perception_disassociation_fugue"
    t.boolean  "perception_disassociation_multiple_personality"
    t.boolean  "perception_disassociation_unremarkable"
    t.boolean  "perception_agnosia_anosognosia"
    t.boolean  "perception_agnosia_autotopagnosia"
    t.boolean  "perception_agnosia_visual_agnosia"
    t.boolean  "perception_agnosia_astereognosia"
    t.boolean  "perception_agnosia_prosopagnosia"
    t.boolean  "perception_agnosia_unremarkable"
    t.boolean  "appearance_hair_color"
    t.boolean  "affect_mood_affective"
    t.boolean  "thought_process_content_absence_of_thought"
    t.boolean  "thought_process_content_obsession"
    t.boolean  "thought_process_content_compulsion"
    t.boolean  "thought_process_content_monomania"
    t.boolean  "thought_process_content_egomania"
    t.boolean  "thought_process_content_hypochondria"
    t.boolean  "thought_process_content_thought_trending"
    t.boolean  "thought_process_content_unremarkable"
    t.string   "thought_process_content"
    t.boolean  "thought_process_delusions_bizarre"
    t.boolean  "thought_process_delusions_mood_congruent"
    t.boolean  "thought_process_delusions_mood_incongruent"
    t.boolean  "thought_process_delusions_somatic"
    t.boolean  "thought_process_delusions_paranoid"
    t.boolean  "thought_process_delusions_persecutory"
    t.boolean  "thought_process_delusions_grandiose"
    t.boolean  "thought_process_delusions_self_accusatory"
    t.boolean  "thought_process_delusions_control"
    t.boolean  "thought_process_delusions_thought_withdrawal"
    t.boolean  "thought_process_delusions_thought_insertion"
    t.boolean  "thought_process_delusions_thought_broadcasting"
    t.boolean  "thought_process_delusions_infidelity"
    t.boolean  "thought_process_delusions_erotomania"
    t.boolean  "thought_process_delusions_pseudolgoa_fantasy"
    t.boolean  "thought_process_delusions_unremarkable"
    t.string   "thought_process_delusions"
    t.boolean  "thought_process_preoccupations_suicidal_ideation_ideation_history"
    t.boolean  "thought_process_preoccupations_suicidal_ideation_previous_attempts"
    t.boolean  "thought_process_preoccupations_suicidal_ideation_current_ideation"
    t.boolean  "thought_process_preoccupations_suicidal_ideation_impulsiveness"
    t.boolean  "thought_process_preoccupations_suicidal_ideation_viable_plan"
    t.boolean  "thought_process_preoccupations_suicidal_ideation_available_means"
    t.boolean  "thought_process_preoccupations_suicidal_ideation_planning_of_affairs"
    t.boolean  "thought_process_preoccupations_suicidal_ideation_unremarkable"
    t.boolean  "thought_process_preoccupations_suicidal_ideation_history_of_violence"
    t.boolean  "thought_process_preoccupations_suicidal_ideation_current_intent_of_violence"
    t.boolean  "thought_process_preoccupations_suicidal_ideation_viable_plan_for_violence"
    t.boolean  "thought_process_preoccupations_suicidal_ideation_means_for_violence_acts"
    t.string   "thought_process_preoccupations_suicidal_ideation"
    t.boolean  "thought_process_phobia_simple"
    t.boolean  "thought_process_phobia_social"
    t.boolean  "thought_process_phobia_acrophobia"
    t.boolean  "thought_process_phobia_claustrophobia"
    t.boolean  "thought_process_phobia_xenophobia"
    t.boolean  "thought_process_phobia_zoophobia"
    t.boolean  "thought_process_phobia_unremarkable"
    t.string   "thought_process_phobia"
    t.boolean  "thought_process_thought_form_mental_disorder"
    t.boolean  "thought_process_thought_form_neurosis"
    t.boolean  "thought_process_thought_form_psychosis"
    t.boolean  "thought_process_thought_form_reality_testing"
    t.boolean  "thought_process_thought_form_illogical_thinking"
    t.boolean  "thought_process_thought_form_autistic_thinking"
    t.boolean  "thought_process_thought_form_magical_thinking"
    t.boolean  "thought_process_thought_form_concrete_thinking"
    t.boolean  "thought_process_thought_form_abstract_thinking"
    t.boolean  "thought_process_thought_form_word_salad"
    t.boolean  "thought_process_thought_form_circumstantiality"
    t.boolean  "thought_process_thought_form_tangential"
    t.boolean  "thought_process_thought_form_incoherence"
    t.boolean  "thought_process_thought_form_perseveration"
    t.boolean  "thought_process_thought_form_condensation"
    t.boolean  "thought_process_thought_form_irrelevant_responses"
    t.boolean  "thought_process_thought_form_loosening"
    t.boolean  "thought_process_thought_form_derailment"
    t.boolean  "thought_process_thought_form_flight_of_ideas"
    t.boolean  "thought_process_thought_form_loose_associations"
    t.boolean  "thought_process_thought_form_blocking"
    t.boolean  "thought_process_thought_form_unremarkable"
    t.string   "thought_process_thought_form"
    t.boolean  "cognition_consciousness_disorientated"
    t.boolean  "cognition_consciousness_clouding"
    t.boolean  "cognition_consciousness_delirium"
    t.boolean  "cognition_consciousness_coma"
    t.boolean  "cognition_consciousness_twilight_state"
    t.boolean  "cognition_consciousness_dreamlike_state"
    t.boolean  "cognition_consciousness_somnolence"
    t.boolean  "cognition_consciousness_unremarkable"
    t.string   "cognition_consciousness"
    t.boolean  "cognition_orientation_to_time"
    t.boolean  "cognition_orientation_to_place"
    t.boolean  "cognition_orientation_to_person"
    t.string   "cognition_orientation"
    t.boolean  "cognition_concentration_focused"
    t.boolean  "cognition_concentration_easily_distracted"
    t.boolean  "cognition_concentration_often_distracted"
    t.boolean  "cognition_concentration_unremarkable"
    t.string   "cognition_concentration"
    t.boolean  "cognition_memory_localized_amnesia"
    t.boolean  "cognition_memory_generalized_amnesia"
    t.boolean  "cognition_memory_selective_amnesia"
    t.boolean  "cognition_memory_short_term_in_tact"
    t.boolean  "cognition_memory_long_term_in_tact"
    t.boolean  "cognition_memory_unremarkable"
    t.string   "cognition_memory"
    t.boolean  "insight_judgement_judgement_critical"
    t.boolean  "insight_judgement_judgement_automatic"
    t.boolean  "insight_judgement_judgement_impaired"
    t.boolean  "insight_judgement_judgement_good"
    t.boolean  "insight_judgement_judgement_fair"
    t.boolean  "insight_judgement_judgement_poor"
    t.boolean  "insight_judgement_judgement_unremarkable"
    t.string   "insight_judgement_judgement"
    t.boolean  "insight_judgement_insight_impairment_in_insight"
    t.boolean  "insight_judgement_insight_denial_of_disorder"
    t.boolean  "insight_judgement_insight_good_insight"
    t.boolean  "insight_judgement_insight_fair_insight"
    t.boolean  "insight_judgement_insight_poor_insight"
    t.boolean  "insight_judgement_insight_unremarkable"
    t.string   "insight_judgement_insight"
  end

  add_index "entries", ["client_id"], :name => "index_entries_on_client_id"

  create_table "roles", :force => true do |t|
    t.string   "name"
    t.integer  "resource_id"
    t.string   "resource_type"
    t.datetime "created_at",    :null => false
    t.datetime "updated_at",    :null => false
  end

  add_index "roles", ["name", "resource_type", "resource_id"], :name => "index_roles_on_name_and_resource_type_and_resource_id"
  add_index "roles", ["name"], :name => "index_roles_on_name"

  create_table "users", :force => true do |t|
    t.string   "email",                  :default => "", :null => false
    t.string   "encrypted_password",     :default => "", :null => false
    t.string   "reset_password_token"
    t.datetime "reset_password_sent_at"
    t.datetime "remember_created_at"
    t.integer  "sign_in_count",          :default => 0
    t.datetime "current_sign_in_at"
    t.datetime "last_sign_in_at"
    t.string   "current_sign_in_ip"
    t.string   "last_sign_in_ip"
    t.datetime "created_at",                             :null => false
    t.datetime "updated_at",                             :null => false
    t.string   "name"
  end

  add_index "users", ["email"], :name => "index_users_on_email", :unique => true
  add_index "users", ["reset_password_token"], :name => "index_users_on_reset_password_token", :unique => true

  create_table "users_roles", :id => false, :force => true do |t|
    t.integer "user_id"
    t.integer "role_id"
  end

  add_index "users_roles", ["user_id", "role_id"], :name => "index_users_roles_on_user_id_and_role_id"

end
