class Entry < ActiveRecord::Base
  attr_accessible :appearance_weight, :appearance_hair, :appearance_other, :appearance_grooming, :appearance_dress, :appearance_weight_obese, 
  :appearance_weight_overweight, :appearance_weight_underweight, :appearance_weight_emaciated, :appearance_weight_unremarkable, :appearance_hair_bizarre, 
  :appearance_hair_unnatural, :appearance_hair_unshaven, :appearance_hair_unremarkable, :appearance_other_wounds, :appearance_other_scars, :appearance_other_tattoos, 
  :appearance_other_jewelry, :appearance_other_glasses, :appearance_other_dental_braces, :appearance_other_unremarkable, :appearance_grooming_disheveled, 
  :appearance_grooming_soiled, :appearance_grooming_body_odor, :appearance_grooming_halitosis, :appearance_grooming_unremarkable, :appearance_dress_undressed, 
  :appearance_dress_underdressed, :appearance_dress_overdressed, :appearance_dress_bizarre, :appearance_dress_militaristic, :appearance_dress_unremarkable, 
  :behavior_walk, :behavior_combativeness, :behavior_repetition, :behavior_overactivity, :behavior_catatonia, :behavior_walk_gait_march, :behavior_walk_limp, 
  :behavior_walk_shuffle, :behavior_walk_assisted, :behavior_walk_unremarkable, :behavior_combativeness_cataplexy, :behavior_combativeness_aggressive, 
  :behavior_combativeness_unremarkable, :behavior_repetition_gestures, :behavior_repetition_twitches, :behavior_repetition_stereotypical, :behavior_repetition_automatism, 
  :behavior_repetition_mimicry, :behavior_repetition_echopraxia, :behavior_repetition_unremarkable, :behavior_overactivity_psychomotor_agitation, 
  :behavior_overactivity_hyperactivity, :behavior_overactivity_tic, :behavior_overactivity_sleepwalking, :behavior_overactivity_compulsion, 
  :behavior_overactivity_unremarkable, :behavior_catatonia_catalepsy, :behavior_catatonia_exited, :behavior_catatonia_stupor, :behavior_catatonia_rigidity, 
  :behavior_catatonia_posturing, :behavior_catatonia_cerea_flexibilitas, :behavior_catatonia_negativism, :behavior_catatonia_unremarkable, :speech_rate_rapid, 
  :speech_rate, :speech_intelligibility, :speech_volume, :speech_quality, :speech_quantity, :speech_rate_slow, :speech_rate_unremarkable, :speech_intelligibility_slurred, 
  :speech_intelligibility_mumbled, :speech_intelligibility_stutters, :speech_intelligibility_accented, :speech_intelligibility_unremarkable, :speech_volume_loud, 
  :speech_volume_whispered, :speech_volume_unremarkable, :speech_quality_hesitant, :speech_quality_emotional, :speech_quality_monotonous, :speech_quality_stereotypical, 
  :speech_quality_unspontaneous, :speech_quality_echolalia, :speech_quality_verbigerative, :speech_quality_unremarkable, :speech_quantity_garrulous, :speech_quantity_talkative, 
  :speech_quantity_responsive, :speech_quantity_taciturn, :speech_quantity_mutism, :speech_quantity_unremarkable, :attitude, :attitude_seductive, :attitude_playful, 
  :attitude_ingratiating, :attitude_friendly, :attitude_cooperative, :attitude_interested, :attitude_attentive, :attitude_frank, :attitude_indifferent, :attitude_evasive, 
  :attitude_defensive, :attitude_hostile, :attitude_unremarkable, :affect_mood, :affect_expression, :affect_appropriateness, :affect_mood_ecstatic, :affect_mood_euphoric, 
  :affect_mood_expansive, :affect_mood_elevated, :affect_mood_euthymic, :affect_mood_dysphoric, :affect_mood_anhedonic, :affect_mood_depressed, :affect_mood_alexithymic, 
  :affect_mood_grieving, :affect_mood_panicked, :affect_mood_fearful, :affect_mood_anxious, :affect_mood_tense, :affect_mood_agitated, :affect_mood_apathetic, 
  :affect_mood_irritable, :affect_mood_angry, :affect_mood_ambivalence, :affect_mood_mood_swings, :affect_mood_anorexia, :affect_mood_insomnia, :affect_mood_hypersomnia, 
  :affect_mood_diminshed_libido, :affect_mood_constipation, :affect_mood_unremarkable, :affect_expression_normal, :affect_expression_restricted, :affect_expression_blunted, 
  :affect_expression_flat, :affect_expression_unremarkable, :affect_appropriateness_appropriate, :affect_appropriateness_inappropriate, :affect_appropriateness_labile, 
  :perception_hallucinations, :perception_disassociation, :perception_agnosia, :perception_hallucinations_hypnagogic, :perception_hallucinations_hypnopompic, 
  :perception_hallucinations_auditory, :perception_hallucinations_visual, :perception_hallucinations_olfactory, :perception_hallucinations_gustatory, 
  :perception_hallucinations_tactile, :perception_hallucinations_somatic, :perception_hallucinations_lilliputian, :perception_hallucinations_mood_congruent, 
  :perception_hallucinations_mood_incongruent, :perception_hallucinations_hallucinosis, :perception_hallucinations_synethesia, :perception_hallucinations_trailing, 
  :perception_hallucinations_unremarkable, :perception_disassociation_hysterical_anesthesia, :perception_disassociation_macropsia, :perception_disassociation_micropsia, 
  :perception_disassociation_depersonalization, :perception_disassociation_derealization, :perception_disassociation_fugue, :perception_disassociation_multiple_personality, 
  :perception_disassociation_unremarkable, :perception_agnosia_anosognosia, :perception_agnosia_autotopagnosia, :perception_agnosia_visual_agnosia, 
  :perception_agnosia_astereognosia, :perception_agnosia_prosopagnosia, :perception_agnosia_unremarkable, :thought_process_content_absence_of_thought, 
  :thought_process_content_obsession, :thought_process_content_compulsion, :thought_process_content_monomania, :thought_process_content_egomania, 
  :thought_process_content_hypochondria, :thought_process_content_thought_trending, :thought_process_content_unremarkable, :thought_process_content, 
  :thought_process_delusions_bizarre, :thought_process_delusions_mood_congruent, :thought_process_delusions_mood_incongruent, :thought_process_delusions_somatic, 
  :thought_process_delusions_paranoid, :thought_process_delusions_persecutory, :thought_process_delusions_grandiose, :thought_process_delusions_self_accusatory, 
  :thought_process_delusions_control, :thought_process_delusions_thought_withdrawal, :thought_process_delusions_thought_insertion, :thought_process_delusions_thought_broadcasting, 
  :thought_process_delusions_infidelity, :thought_process_delusions_erotomania, :thought_process_delusions_pseudolgoa_fantasy, :thought_process_delusions_unremarkable, 
  :thought_process_delusions, :thought_process_preoccupations_suicidal_ideation_ideation_history, :thought_process_preoccupations_suicidal_ideation_previous_attempts, 
  :thought_process_preoccupations_suicidal_ideation_current_ideation, :thought_process_preoccupations_suicidal_ideation_impulsiveness, 
  :thought_process_preoccupations_suicidal_ideation_viable_plan, :thought_process_preoccupations_suicidal_ideation_available_means, 
  :thought_process_preoccupations_suicidal_ideation_planning_of_affairs, :thought_process_preoccupations_suicidal_ideation_unremarkable, 
  :thought_process_preoccupations_suicidal_ideation_history_of_violence, :thought_process_preoccupations_suicidal_ideation_current_intent_of_violence, 
  :thought_process_preoccupations_suicidal_ideation_viable_plan_for_violence, :thought_process_preoccupations_suicidal_ideation_means_for_violence_acts, 
  :thought_process_preoccupations_suicidal_ideation, :thought_process_phobia_simple, :thought_process_phobia_social, :thought_process_phobia_acrophobia, 
  :thought_process_phobia_claustrophobia, :thought_process_phobia_xenophobia, :thought_process_phobia_zoophobia, :thought_process_phobia_unremarkable, 
  :thought_process_phobia, :thought_process_thought_form_mental_disorder, :thought_process_thought_form_neurosis, :thought_process_thought_form_psychosis, 
  :thought_process_thought_form_reality_testing, :thought_process_thought_form_illogical_thinking, :thought_process_thought_form_autistic_thinking, 
  :thought_process_thought_form_magical_thinking, :thought_process_thought_form_concrete_thinking, :thought_process_thought_form_abstract_thinking, 
  :thought_process_thought_form_word_salad, :thought_process_thought_form_circumstantiality, :thought_process_thought_form_tangential, :thought_process_thought_form_incoherence, 
  :thought_process_thought_form_perseveration, :thought_process_thought_form_condensation, :thought_process_thought_form_irrelevant_responses, 
  :thought_process_thought_form_loosening, :thought_process_thought_form_derailment, 
  :thought_process_thought_form_flight_of_ideas, :thought_process_thought_form_loose_associations, :thought_process_thought_form_blocking, 
  :thought_process_thought_form_unremarkable, :thought_process_thought_form, :cognition_consciousness_disorientated, :cognition_consciousness_clouding, 
  :cognition_consciousness_delirium, :cognition_consciousness_coma, :cognition_consciousness_twilight_state, :cognition_consciousness_dreamlike_state, 
  :cognition_consciousness_somnolence, :cognition_consciousness_unremarkable, :cognition_consciousness, :cognition_orientation_to_time, :cognition_orientation_to_place, 
  :cognition_orientation_to_person, :cognition_orientation, :cognition_concentration_focused, :cognition_concentration_easily_distracted, :cognition_concentration_often_distracted, 
  :cognition_concentration_unremarkable, :cognition_concentration, :cognition_memory_localized_amnesia, :cognition_memory_generalized_amnesia, :cognition_memory_selective_amnesia, 
  :cognition_memory_short_term_in_tact, :cognition_memory_long_term_in_tact, :cognition_memory_unremarkable, :cognition_memory, :insight_judgement_judgement_critical, 
  :insight_judgement_judgement_automatic, :insight_judgement_judgement_impaired, :insight_judgement_judgement_good, :insight_judgement_judgement_fair, 
  :insight_judgement_judgement_poor, :insight_judgement_judgement_unremarkable, :insight_judgement_judgement, :insight_judgement_insight_impairment_in_insight, 
  :insight_judgement_insight_denial_of_disorder, :insight_judgement_insight_good_insight, :insight_judgement_insight_fair_insight, :insight_judgement_insight_poor_insight, 
  :insight_judgement_insight_unremarkable, :insight_judgement_insight
  belongs_to :client, :class_name => 'Entry', :foreign_key => 'client_id'
end


